<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addTriggerName</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFIYXNoQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEhhc2hDdXJzb3IoKTsJCgkKCVN0cmlu
ZyBwcm9wZXJ0eV9uYW1lID0gcHJvcF9uYW1lOwoJaWRjLmZpcnN0KCJuYW1lIik7CglTdHJpbmcg
cHJvcGVydHlfdmFsdWUgPSAoU3RyaW5nKWlkYy5nZXRWYWx1ZSgpOwoJaWYgKHByb3BlcnR5X3Zh
bHVlID09IG51bGwpCgkJcmV0dXJuOwoKCXRyeQoJewoJCVN0cmluZyBzdHIgPSBnZXRQcm9wZXJ0
eShwcm9wZXJ0eV9uYW1lKTsKCQlzdHIgKz0gIjsiICsgcHJvcGVydHlfdmFsdWU7CgkJcHJvcGVy
dHlfdmFsdWUgPSBzdHI7CgkJCgkJCS8vIEdldCBzZXJ2ZXIgcHJvcGVydGllcwoJCQlQcm9wZXJ0
aWVzIGNvbmZpZyA9IG5ldyBQcm9wZXJ0aWVzKCk7CgkJCUlucHV0U3RyZWFtIGluX3N0cmVhbSA9
IChJbnB1dFN0cmVhbSkgbmV3IEZpbGVJbnB1dFN0cmVhbShmaWxlX25hbWUpOwoJCQljb25maWcu
bG9hZChpbl9zdHJlYW0pOwoJCQljb25maWcuc2V0UHJvcGVydHkocHJvcGVydHlfbmFtZSwgcHJv
cGVydHlfdmFsdWUpOwoJCQkvLyBTdG9yIHByb3BlcnRpZXMgdG8gZmlsZQoJCQlPdXRwdXRTdHJl
YW0gb3V0ID0gKE91dHB1dFN0cmVhbSkgbmV3IEZpbGVPdXRwdXRTdHJlYW0oZmlsZV9uYW1lKTsK
CQkJY29uZmlnLnN0b3JlKG91dCwgIlNlcnZlciBwcm9wZXJ0eSIpOwoKCQkJb3V0LmZsdXNoKCk7
CgkJCW91dC5jbG9zZSgpOwoJCQlpbl9zdHJlYW0uY2xvc2UoKTsKCgkJCWlkYy5maXJzdCgpOwoJ
CQlpZGMuaW5zZXJ0QWZ0ZXIoICJtZXNzYWdlIiwgIlNldCBwcm9wZXJ0eSAtICIgKyBwcm9wZXJ0
eV92YWx1ZSApOwoJfQoJY2F0Y2ggKEV4Y2VwdGlvbiBlKQoJewoJCWlkYy5maXJzdCgpOwoJCWlk
Yy5pbnNlcnRBZnRlciggIm1lc3NhZ2UiLCAiRXJyb3Igc2V0dGluZyBwcm9wZXJ0eSAtICIgKyBl
LmdldE1lc3NhZ2UoKSk7Cgl9CglpZGMuZGVzdHJveSgpOwo=</value>
</Values>
