<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteTriggerName</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFIYXNoQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEhhc2hDdXJzb3IoKTsJCgkKCVN0cmlu
ZyBwcm9wZXJ0eV9uYW1lID0gcHJvcF9uYW1lOwoJaWRjLmZpcnN0KCJuYW1lIik7CglTdHJpbmcg
cHJvcGVydHlfdmFsdWUgPSAoU3RyaW5nKWlkYy5nZXRWYWx1ZSgpOwoJaWYgKHByb3BlcnR5X3Zh
bHVlID09IG51bGwpCgkJcmV0dXJuOwoKCWlmIChyZW1vdmVWYWx1ZShwcm9wZXJ0eV92YWx1ZSkp
Cgl7CgkJCWlkYy5maXJzdCgpOwoJCQlpZGMuaW5zZXJ0QWZ0ZXIoICJtZXNzYWdlIiwgIlJlbW92
ZSBwcm9wZXJ0eSB2YWx1ZSAtICIgKyBwcm9wZXJ0eV92YWx1ZSApOwoJfQoJZWxzZQoJewoJCQlp
ZGMuZmlyc3QoKTsKCQkJaWRjLmluc2VydEFmdGVyKCAibWVzc2FnZSIsICJFUlJPUiEgUmVtb3Zl
IHByb3BlcnR5IHZhbHVlIC0gIiArIHByb3BlcnR5X3ZhbHVlICk7Cgl9CmlkYy5kZXN0cm95KCk7
</value>
</Values>
